apiVersion: apps/v1
kind: Deployment
metadata:
    name: llm-deployment
    namespace: facture-llm-production
spec:
    replicas: 1
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxUnavailable: 0
            maxSurge: 1
    selector:
        matchLabels:
            app: llm-deployment
    template:
        metadata:
            labels:
                app: llm-deployment
        spec:
            automountServiceAccountToken: false
            containers:
                -   name: llm-deployment
                    image: "rhaversen/facture-llm:0fbc7ad0a502fcc5ee8ba0e8e03d340575631109"
                    imagePullPolicy: Always
                    livenessProbe:
                        httpGet:
                            path: health
                            port: 5008
                        periodSeconds: 10
                        initialDelaySeconds: 15
                        failureThreshold: 5
                    readinessProbe:
                        httpGet:
                            path: health
                            port: 5008
                        periodSeconds: 10
                        initialDelaySeconds: 15
                        failureThreshold: 5
                    ports:
                        -   containerPort: 5008
                    envFrom:
                        -   secretRef:
                                name: llm-secrets
