apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: backend-ingress
    namespace: facture-auth-production
    annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
spec:
    ingressClassName: nginx
    tls:
        -   hosts:
                - auth.facture.live
            secretName: backend-tls
    rules:
        -   host: auth.facture.live
            http:
                paths:
                    # API Path
                    -   path: /api/
                        pathType: Prefix
                        backend:
                            service:
                                name: backend-service
                                port:
                                    number: 80
