apiVersion: apps/v1
kind: Deployment
metadata:
    name: frontend-deployment
    namespace: facture-staging
spec:
    replicas: 1
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxUnavailable: 0
            maxSurge: 1
    selector:
        matchLabels:
            app: frontend-deployment
    template:
        metadata:
            labels:
                app: frontend-deployment
        spec:
            automountServiceAccountToken: false
            containers:
                -   name: frontend-deployment
                    image: "rhaversen/facture-frontend:011dc99fa90f3416d8e1cdac6d1884898fe19f57"
                    imagePullPolicy: Always
                    envFrom:
                        -   secretRef:
                                name: frontend-secrets
                    ports:
                        -   containerPort: 3000
