apiVersion: apps/v1
kind: Deployment
metadata:
    name: frontend-deployment
    namespace: facture-production
spec:
    replicas: 1
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxUnavailable: 0
            maxSurge: 1
    selector:
        matchLabels:
            app: frontend-deployment
    template:
        metadata:
            labels:
                app: frontend-deployment
        spec:
            automountServiceAccountToken: false
            containers:
                -   name: frontend-deployment
                    image: "rhaversen/facture-frontend:3ba721a751bee6685955477ef83039ea027ba1c8"
                    imagePullPolicy: Always
                    ports:
                        -   containerPort: 3000
