apiVersion: apps/v1
kind: Deployment
metadata:
    name: backend-deployment
    namespace: facture-forge-staging
spec:
    replicas: 1
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxUnavailable: 0
            maxSurge: 1
    selector:
        matchLabels:
            app: backend-deployment
    template:
        metadata:
            labels:
                app: backend-deployment
        spec:
            automountServiceAccountToken: false
            containers:
                -   name: backend-deployment
                    image: "rhaversen/facture-forge-backend:84c954826c591a658360b1b32a3ac02834ed37bf"
                    imagePullPolicy: Always
                    livenessProbe:
                        httpGet:
                            path: api/service/livez
                            port: 3001
                        periodSeconds: 10
                        initialDelaySeconds: 15
                        failureThreshold: 5
                    readinessProbe:
                        httpGet:
                            path: api/service/readyz
                            port: 3001
                        periodSeconds: 10
                        initialDelaySeconds: 15
                        failureThreshold: 5
                    ports:
                        -   containerPort: 3001
                    envFrom:
                        -   secretRef:
                                name: backend-secrets
