apiVersion: batch/v1
kind: CronJob
metadata:
  name: tournament-runner-production
  namespace: gaslight-production
spec:
  schedule: "0 0 * * *"  # Runs daily at midnight
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: tournament-runner-production
        spec:
          restartPolicy: Never
          automountServiceAccountToken: false
          containers:
            - name: tournament-runner-production
              image: "rhaversen/gaslight-code-runner:724f61f99018454240f99bfd5ca2dbdad0ca6ef9"
              imagePullPolicy: Always
              envFrom:
                - secretRef:
                    name: tournament-runner-secrets
